Products::ScifiVehicle::VehicleBuilder
int? Products.ScifiVehicle.VehicleBuilder.wheels
Referenced by Products.ScifiVehicle.VehicleBuilder.Build, Products.ScifiVehicle.VehicleBuilder.AddWheels.
Color? Products.ScifiVehicle.VehicleBuilder.vehicleColor
Referenced by Products.ScifiVehicle.VehicleBuilder.Build, Products.ScifiVehicle.VehicleBuilder.WithColor.
List<PropulsionSystem> Products.ScifiVehicle.VehicleBuilder.propulsionSystems
Referenced by Products.ScifiVehicle.VehicleBuilder.Build.
bool Products.ScifiVehicle.VehicleBuilder.canFly
Referenced by Products.ScifiVehicle.VehicleBuilder.Build.
VehicleBuilder Products.ScifiVehicle.VehicleBuilder.WithJetEngine
Referenced by Factory.Abstract.AirplaneFactory.CreateJetPowered, Factory.Abstract.BicycleFactory.CreateJetPowered.
VehicleBuilder Products.ScifiVehicle.VehicleBuilder.WithGasolineEngine
Referenced by Factory.Abstract.AirplaneFactory.CreateGasolinePowered, Factory.Abstract.BicycleFactory.CreateGasolinePowered, Factory.Abstract.FlyingCarFactory.CreateGasolinePowered, Factory.Abstract.FlyingCarFactory.CreateJetPowered, Factory.Abstract.LeaseCarFactory.CreateGasolinePowered, Factory.Abstract.LeaseCarFactory.CreateJetPowered.
VehicleBuilder Products.ScifiVehicle.VehicleBuilder.WithAntiGrav
Referenced by Factory.Abstract.FlyingCarFactory.CreateGasolinePowered, Factory.Abstract.FlyingCarFactory.CreateJetPowered, Factory.Abstract.FlyingCarFactory.CreatePeddlePowered.
VehicleBuilder Products.ScifiVehicle.VehicleBuilder.WithPeddles
Referenced by Factory.Abstract.AirplaneFactory.CreatePeddlePowered, Factory.Abstract.BicycleFactory.CreateJetPowered, Factory.Abstract.BicycleFactory.CreatePeddlePowered, Factory.Abstract.FlyingCarFactory.CreatePeddlePowered, Factory.Abstract.LeaseCarFactory.CreatePeddlePowered.
VehicleBuilder Products.ScifiVehicle.VehicleBuilder.CanFly
Vehicle Products.ScifiVehicle.VehicleBuilder.Build()
References Products.ScifiVehicle.VehicleBuilder.canFly, Products.ScifiVehicle.VehicleBuilder.propulsionSystems, Products.ScifiVehicle.VehicleBuilder.vehicleColor, Products.ScifiVehicle.VehicleBuilder.wheels.
VehicleBuilder Products.ScifiVehicle.VehicleBuilder.AddWheels(int number)
References Products.ScifiVehicle.VehicleBuilder.wheels.
Referenced by Factory.Abstract.AirplaneFactory.CreateGasolinePowered, Factory.Abstract.LeaseCarFactory.CreateGasolinePowered, Factory.Abstract.FlyingCarFactory.CreateGasolinePowered, Factory.Abstract.BicycleFactory.CreateGasolinePowered, Factory.Abstract.AirplaneFactory.CreateJetPowered, Factory.Abstract.FlyingCarFactory.CreateJetPowered, Factory.Abstract.LeaseCarFactory.CreateJetPowered, Factory.Abstract.BicycleFactory.CreateJetPowered, Factory.Abstract.AirplaneFactory.CreatePeddlePowered, Factory.Abstract.LeaseCarFactory.CreatePeddlePowered, Factory.Abstract.FlyingCarFactory.CreatePeddlePowered, Factory.Abstract.BicycleFactory.CreatePeddlePowered.
VehicleBuilder Products.ScifiVehicle.VehicleBuilder.WithColor(Color color)
References Products.ScifiVehicle.VehicleBuilder.vehicleColor.
Referenced by Factory.Abstract.AirplaneFactory.CreateGasolinePowered, Factory.Abstract.LeaseCarFactory.CreateGasolinePowered, Factory.Abstract.FlyingCarFactory.CreateGasolinePowered, Factory.Abstract.BicycleFactory.CreateGasolinePowered, Factory.Abstract.AirplaneFactory.CreateJetPowered, Factory.Abstract.FlyingCarFactory.CreateJetPowered, Factory.Abstract.LeaseCarFactory.CreateJetPowered, Factory.Abstract.BicycleFactory.CreateJetPowered, Factory.Abstract.AirplaneFactory.CreatePeddlePowered, Factory.Abstract.LeaseCarFactory.CreatePeddlePowered, Factory.Abstract.FlyingCarFactory.CreatePeddlePowered, Factory.Abstract.BicycleFactory.CreatePeddlePowered.